# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 435cec283c796cf004fd8b7f1323b2304e4fb5af59a9385b877e1640bce460cb6014ebd5f07a493419bc6d435118154dcdf8bf483901abfe20ae923b2200ec5b

test:
  secret_key_base: a61501026f3b78cea64b2ac74acb7fce77f6cf367994b44d82d64b4313082e03e15992b341c39f8b3d5c05fa0c14476c61ed82a109f45bce02ce3d79dcee9a7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
